services:
  # dashboard and logs database
  db:
    image: postgres:16-alpine
    container_name: litellm_db
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: litellm_password
      POSTGRES_DB: litellm_db
    restart: unless-stopped
    networks:
      - cat-network

  # cache for routing decisions and model metadata (optional but recommended)
  redis:
    image: redis:alpine
    container_name: litellm_redis
    restart: unless-stopped
    networks:
      - cat-network

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm_proxy
    ports:
      - "4000:4000"
    volumes:
      - ./litellm/config.yaml:/app/config.yaml
    depends_on:
      - db
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY} # proxy password
      - DATABASE_URL=postgresql://litellm:litellm_password@db:5432/litellm_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      # - LITELLM_LOG=DEBUG
      # - LANGFUSE_DEBUG=True
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    restart: unless-stopped
    networks:
      - cat-network

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - ${CORE_PORT:-1865}:80
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - /app/cat/plugins/vanna/training # exclude folder vanna/training from docker
      - ./data:/app/cat/data
      - ./doc:/app/cat/doc # folder to manage user files
      - ./logs:/app/cat/logs  # logs folder
    env_file:
      - .env  # no file .env in the container — Docker reads the values and writes them directly as environment variables
    depends_on:
      - litellm # ensure the core starts after the proxy to allow it to connect to the proxy at startup
    restart: unless-stopped
    networks:
      - cat-network # connect to the same network of litellm to allow communication

networks:
  cat-network:
    driver: bridge