services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - ${CORE_PORT:-1865}:80
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - /app/cat/plugins/vanna/training # exclude folder vanna/training from docker
      - ./data:/app/cat/data
      - ./temp:/app/cat/temp # folder to manage user files
      - ./logs:/app/cat/logs  # logs folder
    env_file:
      - .env  # no file .env in the container — Docker reads the values and write them directly as environment variables